const SURVEY_DOMAIN_ERROR_CODES = Object.freeze({
  INVALID_INTERIOR_ANGLE: 'INVALID_INTERIOR_ANGLE',
  INVALID_WALL_LENGTH: 'INVALID_WALL_LENGTH',
  INVALID_WALL_THICKNESS: 'INVALID_WALL_THICKNESS',
  INVALID_OPENING_SIZE: 'INVALID_OPENING_SIZE',
  INVALID_OPENING_DEPTH: 'INVALID_OPENING_DEPTH',
  INVALID_OPENING_SILL_HEIGHT: 'INVALID_OPENING_SILL_HEIGHT',
  INVALID_OPENING_OFFSET: 'INVALID_OPENING_OFFSET',
  OPENING_SPLIT_CONFLICT: 'OPENING_SPLIT_CONFLICT',
  CURSOR_REQUIRED_FOR_DIRECTION: 'CURSOR_REQUIRED_FOR_DIRECTION',
  STRAIGHT_MODE_REQUIRED_FOR_DIRECTION: 'STRAIGHT_MODE_REQUIRED_FOR_DIRECTION',
  ORTHOGONAL_DIRECTION_REQUIRED: 'ORTHOGONAL_DIRECTION_REQUIRED',
  DIAGONAL_PREVIEW_REQUIRED: 'DIAGONAL_PREVIEW_REQUIRED',
  LATEST_DIAGONAL_NOT_EDITABLE: 'LATEST_DIAGONAL_NOT_EDITABLE',
  LATEST_DIAGONAL_INCOMPLETE: 'LATEST_DIAGONAL_INCOMPLETE',
  WALL_PREVIEW_REQUIRED: 'WALL_PREVIEW_REQUIRED',
  WALL_OVERLAP: 'WALL_OVERLAP',
  CLOSURE_OUT_OF_TOLERANCE: 'CLOSURE_OUT_OF_TOLERANCE',
  UNSAFE_CLOSURE: 'UNSAFE_CLOSURE',
  PARTITION_SPLIT_UNSAFE: 'PARTITION_SPLIT_UNSAFE',
  SHARED_BOUNDARY_DISCONNECTED: 'SHARED_BOUNDARY_DISCONNECTED',
  CLOSED_SPACE_REQUIRED: 'CLOSED_SPACE_REQUIRED',
  ROOM_NAME_REQUIRED: 'ROOM_NAME_REQUIRED',
  ROOM_NAME_TOO_LONG: 'ROOM_NAME_TOO_LONG',
  WALL_REQUIRED_FOR_OPENING: 'WALL_REQUIRED_FOR_OPENING',
  OPENING_REQUIRED: 'OPENING_REQUIRED',
  OPENING_REMEASURE_CONFLICT: 'OPENING_REMEASURE_CONFLICT',
  REMEASURE_SELECTION_REQUIRED: 'REMEASURE_SELECTION_REQUIRED',
  SHARED_WALL_REMEASURE_UNSUPPORTED: 'SHARED_WALL_REMEASURE_UNSUPPORTED',
  CLOSED_REMEASURE_UNSAFE: 'CLOSED_REMEASURE_UNSAFE',
  INVALID_REMEASURE_ENDPOINT: 'INVALID_REMEASURE_ENDPOINT',
  REMEASURE_CONNECTED_ENDPOINT: 'REMEASURE_CONNECTED_ENDPOINT',
  REMEASURE_LENGTH_TOO_SHORT: 'REMEASURE_LENGTH_TOO_SHORT'
});

class SurveyDomainError extends Error {
  constructor(code, details) {
    super(code);
    this.name = 'SurveyDomainError';
    this.code = code;
    this.details = Object.assign({}, details || {});
  }
}

function createSurveyDomainError(code, details) {
  return new SurveyDomainError(code, details);
}

function isSurveyDomainError(error) {
  return error instanceof SurveyDomainError || !!(
    error && error.name === 'SurveyDomainError' && error.code
  );
}

module.exports = {
  SURVEY_DOMAIN_ERROR_CODES,
  SurveyDomainError,
  createSurveyDomainError,
  isSurveyDomainError
};
