services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-floor-planner-admin
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: smart-floor-planner-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
